export const HANDLE_LIKE_REQUEST = "HANDLE_LIKE_REQUEST";
export const HANDLE_LIKE_SUCCESS = "HANDLE_LIKE_SUCCESS";
export const HANDLE_LIKE_FAIL = "HANDLE_LIKE_FAIL";
export const HANDLE_LIKE_RESET = "HANDLE_LIKE_RESET";

export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_FAIL = "GET_ALL_POSTS_FAIL";

export const APPROVE_POST_REQUEST = "APPROVE_POST_REQUEST";
export const APPROVE_POST_SUCCESS = "APPROVE_POST_SUCCESS";
export const APPROVE_POST_FAIL = "APPROVE_POST_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const CREATE_POST_RESET = "CREATE_POST_RESET";

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAIL = "EDIT_POST_FAIL";
export const EDIT_POST_RESET = "EDIT_POST_RESET";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";
export const GET_POST_RESET = "GET_POST_RESET";
