export const POSTER_REGISTER_REQUEST = "POSTER_REGISTER_REQUEST";
export const POSTER_REGISTER_SUCCESS = "POSTER_REGISTER_SUCCESS";
export const POSTER_REGISTER_FAIL = "POSTER_REGISTER_FAIL";

export const POSTER_LOGIN_REQUEST = "POSTER_LOGIN_REQUEST";
export const POSTER_LOGIN_SUCCESS = "POSTER_LOGIN_SUCCESS";
export const POSTER_LOGIN_FAIL = "POSTER_LOGIN_FAIL";
export const POSTER_LOGOUT = "POSTER_LOGOUT";

export const POSTER_PROFILE_REQUEST = "POSTER_PROFILE_REQUEST";
export const POSTER_PROFILE_SUCCESS = "POSTER_PROFILE_SUCCESS";
export const POSTER_PROFILE_FAIL = "POSTER_PROFILE_FAIL";

export const POSTER_PROFILE_UPDATE_REQUEST = "POSTER_PROFILE_UPDATE_REQUEST";
export const POSTER_PROFILE_UPDATE_SUCCESS = "POSTER_PROFILE_UPDATE_SUCCESS";
export const POSTER_PROFILE_UPDATE_FAIL = "POSTER_PROFILE_UPDATE_FAIL";

export const GET_ALL_POSTERS_REQUEST = "GET_ALL_POSTERS_REQUEST";
export const GET_ALL_POSTERS_SUCCESS = "GET_ALL_POSTERS_SUCCESS";
export const GET_ALL_POSTERS_FAIL = "GET_ALL_POSTERS_FAIL";

export const APPROVE_POSTER_REQUEST = "APPROVE_POSTER_REQUEST";
export const APPROVE_POSTER_SUCCESS = "APPROVE_POSTER_SUCCESS";
export const APPROVE_POSTER_FAIL = "APPROVE_POSTER_FAIL";

export const DELETE_POSTER_REQUEST = "DELETE_POSTER_REQUEST";
export const DELETE_POSTER_SUCCESS = "DELETE_POSTER_SUCCESS";
export const DELETE_POSTER_FAIL = "DELETE_POSTER_FAIL";
